# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: chbadad <chbadad@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/16 16:19:00 by chbadad           #+#    #+#              #
#    Updated: 2022/01/30 17:42:46 by chbadad          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# ==== DEFS =====

NAME = minishell

SDIR = srcs/

# Builtins
B_DIR = builtins/
SFILES = cd.c \
		cd_2.c \
		pwd.c \
		export_env.c \
		unset_print_env.c \
		echo.c \
		exit_builtin.c
SRCS = $(addprefix ${SDIR}, $(addprefix ${B_DIR}, ${SFILES}))

# Builtins env utils
B_E_DIR = builtins/env_utils/
SFILES +=	env_hashtables.c \
			env_utils.c \
			env_char.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${B_E_DIR}, ${SFILES}))

# Lexer
L_DIR = lexer/
SFILES +=	lexer_linked_list.c \
			lexer_state_machines.c \
			lexer_tokenise_op.c \
			lexer_tokenizer.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${L_DIR}, ${SFILES}))

# Parser
P_DIR = parser/
SFILES +=	command_list_utils.c \
			stack_utils.c \
			parser_remove_quotes.c \
			parser_remove_quote_2.c \
			parser_remove_quote_3.c \
			parser_remove_quote_4.c \
			state_machine.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${P_DIR}, ${SFILES}))

# Parser Rules
P_R_DIR = parser/rules/
SFILES += 	rules_1_7.c \
			rules_8_13.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${P_R_DIR}, ${SFILES}))

# Parser States
P_S_DIR = parser/states/
SFILES += 	state_0.c \
			states_1_5.c \
			states_6_10.c \
			states_11_15.c \
			states_16_18.c \
			states_19_20.c \
			states_21.c \
			states_22_25.c \
			states_26_30.c \
			states_31_32.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${P_S_DIR}, ${SFILES}))

# Exec
EX_DIR = exec/
SFILES += exec_utils.c \
		  execution.c \
		  give_pipefd.c \
		  heredoc.c \
		  heredoc_utils.c \
		  misc_tools.c \
		  pipe_distribution.c \
		  redirection.c \
		  clear_program.c \
		  access_utils.c \
		  get_next_line.c \
		  get_next_line_utils.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${EX_DIR}, ${SFILES}))

# Error handling
E_DIR = error_handling/
SFILES += errors.c \
		  exec_error.c
SRCS += $(addprefix ${SDIR}, $(addprefix ${E_DIR}, ${SFILES}))

# Minishell
SFILES += minishell.c \
		  signal_handling.c \
		  signal_specifics.c \
		  ressources.c
SRCS += $(addprefix ${SDIR}, ${SFILES})

ODIR = objs/
OBJS = $(addprefix ${ODIR}, ${SFILES:.c=.o})
LIB_EXE = libft/libft.a

GCC = gcc
RM = rm -rf
CCFLAGS = -Wall -Wextra -Werror -g# -fsanitize=address
INCL = -I ./includes -I ./libft
LIB_COMPIL = -L./libft -lft
LIB_READLINE = -lreadline


# ==== RULES ====

all: ${ODIR} ${NAME}

${ODIR}:
	mkdir ${ODIR}

${LIB_EXE}:
	@make -C libft

${NAME}: ${LIB_EXE} ${OBJS}
	${GCC} ${CCFLAGS} ${OBJS} -o ${NAME} ${INCL} ${LIB_COMPIL} ${LIB_READLINE}

${ODIR}%.o: ${SDIR}${B_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${B_E_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${L_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${P_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${P_R_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${P_S_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${E_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}${EX_DIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

${ODIR}%.o: ${SDIR}%.c
	${GCC} ${CCFLAGS} -c $< -o $@ ${INCL}

clean:
	${RM} ${ODIR}
	@make -C libft clean
fclean:
	${RM} ${ODIR}
	${RM} ${NAME}
	@make -C libft fclean
re: fclean all

.PHONY:	all clean re fclean